version: '2'
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    
  vote:
    image: voting-app
    ports:
      - 5000:80

  result:
    image: result-app
    ports:
      - 5001:80

  worker:
    image: worker
    links:
      - redis
      - db